---
title: "calibration-stocks-maxlikely"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010, 2020]
startyear: 2010
regions: DEU
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONTYPE: stocks
  TARGETFUNCTION: maxlikely
# parameters for calibration
parameters:
  alpha: 0.1
  iteration: 3
...
