---
title: "calibMinimal-2020"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010, 2020]
startyear: 2010
regionmapping: "inst/input/regionmappingEUplus.csv"
regions: DEU
ignoreShell: TRUE
# data
# startingPoint: "output/small_2023-04-17_11.04.00/abort.gdx"
...
