---
title: "calibration-simple-lowEhp1-const-agg-2040"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010, 2020, 2030, 2040]
startyear: 2010
calibperiods: 2010
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
reportingTemplate: ignoreShell_onlyRes
# switches
switches:
  RUNTYPE: calibrationSimple
  CALIBRATIONTYPE: flows
  CALIBRATIONRESOLUTION: aggregate
  CALIBRATIONINPUT: file
  CALIBRATIONLOWOP: "ehp1"
  TARGETFUNCTION: minsquare
  CALIBRATIONSTEP: constant
  CALIBRATEPRICESENS: FALSE
# parameters for calibration
parameters:
  alpha: 80
  iteration: 100
...
