---
title: "calibration-stocks-2010"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010]
startyear: 2010
calibperiods: 2010
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONTYPE: stockszero
  CALIBRATIONINPUT: data
  TARGETFUNCTION: minsquare
  CALIBRATIONLOG: TRUE
  CALIBRATEPRICESENS: NORMAL
# parameters for calibration
parameters:
  alpha: 10
  iteration: 10
...
