---
title: "calibration-mtch-12-06-fixedB-start2000"
basedOn: "calibration.yaml"
granularity: lowGran
# switches
switches:
  # AGGREGATEDIM: vin
  # FIXTOTALS: stock
  FIXEDBUILDINGS: TRUE
# parameters for calibration
calibrationParameters:
  stepSizeInit: 80
  iterations: 10
  # sensitivityArmijo: 0.01
  # modifyData: FALSE
...
