---
title: "calibration-randomCost"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010]
startyear: 2010
regionmapping: "inst/input/regionmappingEUplus.csv"
regions: DEU
ignoreShell: TRUE
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONTYPE: stocks
  CALIBRATIONINPUT: randomCost
  TARGETFUNCTION: minsquare
  CALIBRATIONLOG: TRUE
# parameters for calibration
parameters:
  alpha: 0.1
  iteration: 2
  randDev: 20
...
