---
title: "calibration-mtch-15-05-fixTot-aggVin"
basedOn: "default.yaml"
# scope and resolution
periods: [2005, 2010, 2015]
startyear: 2010
calibperiods: 2010
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
inputRevision: 0.8.3
ignoreShell: TRUE
reportingTemplate: ignoreShell_onlyRes
ltEternalShare: 0.05
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONMETHOD: logit
  AGGREGATEDIM: vin
  FIXTOTALS: TRUE
# parameters for calibration
calibrationParameters:
  stepSizeInit: 80
  iterations: 2
  iterationsArmijo: 20
  sensitivityArmijo: 0.01
  modifyData: FALSE
...
