---
title: "calibration-lowEhp1-min-2010"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010]
startyear: 2010
calibperiods: 2010
regionmapping: "input/regionmappingEUplus.csv"
regions: DEU
ignoreShell: TRUE
minimal: TRUE
reportingTemplate: "/p/tmp/ricardar/reportbrick-tmpl/ignoreShell_min"
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONTYPE: flows
  CALIBRATIONINPUT: file
  CALIBRATIONLOWOP: "ehp1"
  TARGETFUNCTION: minsquare
  CALIBRATIONLOG: TRUE
  CALIBRATEPRICESENS: NORMAL
# parameters for calibration
parameters:
  alpha: 10
  iteration: 3
...
