---
title: "calibration-stocks-mtch-15-05-fixTot"
basedOn: "calibration.yaml"
# switches
switches:
  CALIBRATIONMETHOD: optimization
  TARGETFUNCTION: minsquare
  CALIBRATIONTYPE: stocks
  # AGGREGATEDIM: vin
  FIXTOTALS: stock
# parameters for calibration
calibrationParameters:
  stepSizeInit: 10
  # iterations: 5
  # iterationsArmijo: 20
...
