---
title: "calibration-simple-lowEhp1-const-agg-2010"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010]
startyear: 2010
calibperiods: 2010
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
reportingTemplate: ignoreShell_onlyRes
inputRevision: "0.6"
intangCostFiles: {ren: '/p/tmp/ricardar/aux/brickAssump/costIntangRen-noStatQuo.csv'}
# switches
switches:
  RUNTYPE: calibrationSimple
  CALIBRATIONTYPE: flows
  CALIBRATIONRESOLUTION: aggregate
  CALIBRATIONINPUT: file
  CALIBRATIONLOWOP: "ehp1"
  TARGETFUNCTION: minsquare
  CALIBRATIONSTEP: constant
  CALIBRATEPRICESENS: FALSE
# parameters for calibration
parameters:
  alpha: 20
  iteration: 100
...
