---
title: "calibration-2010"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010]
startyear: 2010
regionmapping: "inst/input/regionmappingEUplus.csv"
regions: DEU
ignoreShell: TRUE
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONTYPE: flows
  CALIBRATIONINPUT: randomTarget
  TARGETFUNCTION: minsquare
# parameters for calibration
parameters:
  alpha: 0.1
  iteration: 1
...
