---
title: "calibration-randomCost-min-2040"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010, 2020, 2030, 2040]
startyear: 2010
calibperiods: 2010
regionmapping: "input/regionmappingEUplus.csv"
regions: DEU
ignoreShell: TRUE
minimal: TRUE
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONTYPE: flows
  CALIBRATIONINPUT: randomCost
  TARGETFUNCTION: minsquare
# parameters for calibration
parameters:
  alpha: 0.1
  iteration: 30
  randDev: 20
...
