---
title: "calibration"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2005, 2010]
startyear: 2005
calibperiods: 2005
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
reportingTemplate: ignoreShell_onlyRes
ltEternalShare: 0.05
statusQuoPreference: 0
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONMETHOD: logit
# parameters for calibration
calibrationParameters:
  stepSizeInit: 80
  iterations: 5
  iterationsArmijo: 20
  sensitivityArmijo: 0.04
  modifyData: FALSE
...
