---
title: "calibration-lowEhp1-adapt-sig0_005-2010"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010]
startyear: 2010
calibperiods: 2010
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
reportingTemplate: ignoreShell_onlyRes
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONTYPE: flows
  CALIBRATIONINPUT: file
  CALIBRATIONLOWOP: "ehp1"
  TARGETFUNCTION: minsquare
  CALIBRATIONSTEP: adaptive
  CALIBRATEPRICESENS: FALSE
# parameters for calibration
parameters:
  alpha: 20
  sigma: 0.005
  iteration: 10
...
