---
title: iamc_skeptic
basedOn: iamc_base.yaml
# regions: DEU
regions: [AUT, BEL, BGR, CYP, CZE, DEU, DNK, ESP, EST, FIN, FRA, GBR, GRC, HRV,
          HUN, IRL, ITA, LTU, LUX, LVA, MLT, NLD, POL, PRT, ROU, SVK, SVN, SWE]
startyear: 2025
iamcSwitch: ["reel", "ehp1", "biom", "dihe", "carbonPrice"]
markupPct: 0.3
compareGdx: "output/iamc_base_2023-07-06_16.43.59/output.gdx"
historic: "output/iamc_base_2023-07-06_16.43.59"
...
