---
title: iamc_base
# scope and resolution
periods: [2000, 2005, 2010, 2015, 2020, 2022, 2025, 2030, 2035, 2040, 2045,
          2050, 2060, 2070]
startyear: 2005
endyear: 2050
regions: [AUT, BEL, BGR, CYP, CZE, DEU, DNK, ESP, EST, FIN, FRA, GBR, GRC, HRV,
          HUN, IRL, ITA, LTU, LUX, LVA, MLT, NLD, POL, PRT, ROU, SVK, SVN, SWE]
#regions: [DEU, ESP, FRA, GBR, ITA, NLD, POL]
#regions: HRV
#startingPoint: /p/tmp/krekeler/dev/brick/output/iamc_base_2023-07-06_21.52.10
switches:
  SOLVEPROBLEM: lpnlp
...
