---
title: iamc_statusquo
basedOn: iamc_base.yaml
# regions: DEU
regions: [DEU, FIN, POL]
# startyear: 2025
iamcSwitch: "statusquo"
markupPct: 0.3
# compareGdx: "output/iamc_base_2023-07-06_16.43.59/output.gdx"
# historic: "output/iamc_base_2023-11-06_16.45.35"
...
