---
title: iamc_statusquo_price
basedOn: iamc_base.yaml
# regions: DEU
regions: [DEU, FIN, POL]
startyear: 2025
iamcSwitch: "statusquo"
carbonPrice: {2022: 0, 2030: 300, 2050: 500}
# compareGdx: "output/iamc_base_2023-07-06_16.43.59/output.gdx"
historic: "output/iamc_base_2023-11-06_16.45.35"
...
