---
title: "fastTestRun-2010"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010]
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
reportingTemplate: "onlyRes"
...
