---
title: "fastTestRun"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010, 2020, 2030, 2040, 2050]
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
...
