---
title: "noShellEUR-2040"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010, 2020, 2030, 2040]
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ignoreShell: TRUE
# minimal: TRUE
reportingTemplate: "ignoreShell_onlyRes"
...
