---
title: "quickFullRun-2040"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010, 2020, 2030, 2040]
startyear: 2010
regionmapping: "input/regionmappingEUplus.csv"
regions: DEU
ignoreShell: TRUE
minimal: TRUE
...
