---
title: "runFromCalibStocks-rd200-2010"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2010, 2020, 2030, 2040, 2050, 2060, 2070]
startyear: 2010
regionmapping: "input/regionmappingEUplus.csv"
regions: DEU
ignoreShell: TRUE
calibGdx: "calibRes/calibStocks-rd200-2010.gdx"
# switches
switches:
  CALIBRATIONINPUT: randomCost
# parameters for calibration
parameters:
  randDev: 200
...
